.TH "PKTRIGGERCORD" "1"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pktriggercord - Pentax DSLR tethering software
.SH "SYNOPSIS"
.SY pktriggercord
.OP \-\-debug 
.YS
.PP
Syntax shows only long option names.
.SH "DESCRIPTION"
.PP
pkTriggerCord is a cross\-platform Pentax DSLR tethering software, and
pktriggercord is a gui interface for it\.
.PP
\fB\-\-debug\fR
.RS 4
Debug info\.
.RE
.SH "SEE ALSO"
.PP
\fIThe pktriggercord.melda.info website\fR\&[1],
.\" .SH "AUTHORS"
.\" .PP
.\" \fBAndras Salamon\fR
.\" .sp -1n
.\" .IP "" 4
.\" Author.
.SH "NOTES"
.IP " 1." 4
The pktriggercord.melda.info website
.RS 4
\%http://pktriggercord.melda.info/
.RE

