#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define PLAYERONE_VERSION_MAJOR @PLAYERONE_VERSION_MAJOR@
#define PLAYERONE_VERSION_MINOR @PLAYERONE_VERSION_MINOR@

#endif // CONFIG_H
