#!/bin/sh
# postinst script for indi-asi-power

if [ -x /run/systemd/system ]; then
    sudo systemctl daemon-reload
    sudo systemctl enable pigpiod.service
    sudo systemctl start pigpiod.service
fi
