#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define ASTROASIS_VERSION_MAJOR @ASTROASIS_VERSION_MAJOR@
#define ASTROASIS_VERSION_MINOR @ASTROASIS_VERSION_MINOR@

#endif // CONFIG_H
