#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define ASTROLINK4_VERSION_MAJOR @ASTROLINK4_VERSION_MAJOR@
#define ASTROLINK4_VERSION_MINOR @ASTROLINK4_VERSION_MINOR@

#endif // CONFIG_H
