name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu", "debian", "fedora"]

    container:
      image: ghcr.io/indilib/${{ matrix.container }}

    steps:
      - name: Get INDI 3rd Party Sources
        uses: actions/checkout@v2
        with:
          path: indi-3rdparty

      - name: Get INDI Core Package
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: indilib/indi
          branch: master
          workflow: default.yml
          name: indi-core-package-${{ matrix.container }}
          path: ./packages/

      - name: Install INDI Core
        run: $(command -v sudo) tar -hxvf packages/indi-core-package.tar --strip-components=1 -C /

      - name: Build INDI 3rd Party Libraries
        run: indi-3rdparty/scripts/indi-3rdparty-libs-build.sh

      - name: Install INDI 3rd Party Libraries
        run: indi-3rdparty/scripts/indi-3rdparty-libs-install.sh

      - name: Build INDI 3rd Party Drivers
        run: indi-3rdparty/scripts/indi-3rdparty-build.sh

      - name: Install INDI 3rd Party Drivers
        run: indi-3rdparty/scripts/indi-3rdparty-install.sh
